### ISSUE TITLE
Utf-8 encoding support!

### ISSUE THREAD

**Issue by at1323** [mittelmark/microemacs#4]
Hello, friends. 
      This software is very convenient for my daily use, but could you please add support for UTF-8 encoding? Thank you.

**Comment by mittelmark** [comment]
Thank you for your issue report. Direct UTF-8 support is not an easy task. It is more for the long-term support.
For the terminal version on a Unix machine (Linux, MacOS) you could use [luit](https://linux.die.net/man/1/luit)  to run MIcroEmacs. This translates between an UTF-8 terminal and your used MicroEmacs encodings.

 luit -encoding ISO-8859-15 mecb 

What platform (Windows, MacOS, Linux) and what application type (Terminal, GUI) are you using?

**Comment by at1323** [comment]
Thanks too much!
Windows, macos15, debian linux, I usually use C for embedded systems development. I can perform tests using only the terminal,but I need to study luit first. Thank you.

**Comment by mittelmark** [comment]
I added a little Bash wrapper script which ensures that luit is running with the current ME encoding selection:

https://github.com/mittelmark/microemacs/blob/master/bin/encoding.sh

make this file executable, rename it to mecu for instance and move that into a folder of your PATH variable. if mecb is not your executable filename you should rename the ME variable in the script.

That should work at least on Linux and MacOS.

BTW: We have as well a newer ME version (ME24) which probably will not need luit anymore. You can find it here - https://github.com/bjasspa/jasspa

**Comment by at1323** [comment]
I didn't notice there was a new version, sorry! Let me try again.
